# Generated by Django 2.2.24 on 2022-07-16 01:10

from django.db import migrations
from django.db.models import F, Q


def fill_new_building(apps,schema_editor):
    Flat = apps.get_model('property','Flat')
    Flat.objects.update(new_building=Q(construction_year__gte=2015))
    Flat.objects.filter(construction_year__isnull=True).update(new_building=False)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building)
    ]
