# Generated by Django 2.2.24 on 2022-07-17 14:42
import phonenumbers
from django.db import migrations


def fill_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    changed_flats = []
    for flat in Flat.objects.all():
        phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phone):
            flat.owner_pure_phone = f'+{phone.country_code}{phone.national_number}'
            changed_flats.append(flat)
    Flat.objects.bulk_update(changed_flats, ['owner_pure_phone'], batch_size=200)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone),
    ]
