# Generated by Django 2.2.24 on 2022-07-19 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0012_auto_20220719_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
