# Generated by Django 2.2.24 on 2022-07-21 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20220720_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conplaint',
            name='problem_flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='property.Flat', verbose_name='Квартира, на которую жаловались'),
        ),
        migrations.AlterField(
            model_name='conplaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conplaints', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
    ]
