# Generated by Django 2.2.24 on 2022-07-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20220722_0020'),
    ]

    operations = [
        migrations.RenameModel('Conplaint', 'Complaint')
    ]
